[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip/=lib/ccip/",
    "@chainlink/local/=lib/chainlink-local/",
]
rpc_endpoints = { sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/rg7vJQQ_ExcioT9A85OU3WQgbLVCOs0J", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/rg7vJQQ_ExcioT9A85OU3WQgbLVCOs0J" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
